FROM node:20-alpine

WORKDIR /usr/src/app

COPY ./packages /usr/src/app/packages
COPY ./apps/web /usr/src/app/apps/web
COPY package.json /usr/src/app/package.json
COPY pnpm-lock.yaml /usr/src/app/pnpm-lock.yaml
COPY turbo.json /usr/src/app/turbo.json



RUN npm install -g pnpm && pnpm install --frozen-lockfile

EXPOSE 3001

WORKDIR /usr/src/app/apps/web

RUN pnpm build

CMD ["pnpm", "start"]
