FROM node:20-alpine

WORKDIR /usr/src/app

COPY ./packages ./packages
COPY ./pnpm-lock.yaml ./pnpm-lock.yaml

COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json

COPY ./apps/http-server ./apps/http-server


RUN npm install -g pnpm && pnpm install --frozen-lockfile
RUN pnpm db:generate
RUN pnpm build


EXPOSE 8080

CMD ["pnpm", "start:server"]



