FROM node:20-alpine

WORKDIR /usr/src/app

COPY ./packages ./packages
COPY ./pnpm-lock.yaml ./pnpm-lock.yaml

COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json

COPY ./apps/web ./apps/web


RUN npm install -g pnpm && pnpm install --frozen-lockfile --filter ./apps/web...
RUN pnpm build

EXPOSE 3001

CMD ["pnpm", "start:landing"]
