name: Deploy the backend
on:
  push:
    branches:
      - main

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push 
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile.server
          build-args: DATABASE_URL=${{ secrets.DATABASE_URL }}
          push: true
          tags: kunal3256/cloki-backend:${{ github.sha }}

      - name: Deploy to the VM
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/ssh_key
          chmod 700 ~/ssh_key
          ssh -o StrictHostKeyChecking=no -i ~/ssh_key ubuntu@13.60.172.68 -t "
            sudo docker stop cloki-server || true
            sudo docker rm cloki-server || true

            # Remove old unused images
            sudo docker image prune -f

            # Run the new container
            sudo docker run --name cloki-server -d -p 8080:8080 \
            -e OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} \
            -e LANGSMITH_ENDPOINT=${{ secrets.LANGSMITH_ENDPOINT }} \
            -e LANGSMITH_API_KEY=${{ secrets.LANGSMITH_API_KEY }} \
            -e LANGSMITH_TRACING=${{ secrets.LANGSMITH_TRACING }} \
            kunal3256/cloki-backend:${{ github.sha }}
          "
